// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock.go -package=tracks
//

// Package tracks is a generated GoMock package.
package tracks

import (
	context "context"
	reflect "reflect"

	spotify "github.com/jetaimejeteveux/music-catalog/internal/repository/spotify"
	gomock "go.uber.org/mock/gomock"
)

// MockSpotifyOutbond is a mock of SpotifyOutbond interface.
type MockSpotifyOutbond struct {
	ctrl     *gomock.Controller
	recorder *MockSpotifyOutbondMockRecorder
	isgomock struct{}
}

// MockSpotifyOutbondMockRecorder is the mock recorder for MockSpotifyOutbond.
type MockSpotifyOutbondMockRecorder struct {
	mock *MockSpotifyOutbond
}

// NewMockSpotifyOutbond creates a new mock instance.
func NewMockSpotifyOutbond(ctrl *gomock.Controller) *MockSpotifyOutbond {
	mock := &MockSpotifyOutbond{ctrl: ctrl}
	mock.recorder = &MockSpotifyOutbondMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotifyOutbond) EXPECT() *MockSpotifyOutbondMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockSpotifyOutbond) Search(ctx context.Context, query string, limit, offset int) (*spotify.SpotifySearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, limit, offset)
	ret0, _ := ret[0].(*spotify.SpotifySearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSpotifyOutbondMockRecorder) Search(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSpotifyOutbond)(nil).Search), ctx, query, limit, offset)
}
