// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock.go -package=tracks
//

// Package tracks is a generated GoMock package.
package tracks

import (
	context "context"
	reflect "reflect"

	trackactivities "github.com/jetaimejeteveux/music-catalog/internal/models/trackactivities"
	spotify "github.com/jetaimejeteveux/music-catalog/internal/repository/spotify"
	gomock "go.uber.org/mock/gomock"
)

// MockSpotifyOutbond is a mock of SpotifyOutbond interface.
type MockSpotifyOutbond struct {
	ctrl     *gomock.Controller
	recorder *MockSpotifyOutbondMockRecorder
	isgomock struct{}
}

// MockSpotifyOutbondMockRecorder is the mock recorder for MockSpotifyOutbond.
type MockSpotifyOutbondMockRecorder struct {
	mock *MockSpotifyOutbond
}

// NewMockSpotifyOutbond creates a new mock instance.
func NewMockSpotifyOutbond(ctrl *gomock.Controller) *MockSpotifyOutbond {
	mock := &MockSpotifyOutbond{ctrl: ctrl}
	mock.recorder = &MockSpotifyOutbondMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotifyOutbond) EXPECT() *MockSpotifyOutbondMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockSpotifyOutbond) Search(ctx context.Context, query string, limit, offset int) (*spotify.SpotifySearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, limit, offset)
	ret0, _ := ret[0].(*spotify.SpotifySearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSpotifyOutbondMockRecorder) Search(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSpotifyOutbond)(nil).Search), ctx, query, limit, offset)
}

// MocktrackActivitiesRepository is a mock of trackActivitiesRepository interface.
type MocktrackActivitiesRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktrackActivitiesRepositoryMockRecorder
	isgomock struct{}
}

// MocktrackActivitiesRepositoryMockRecorder is the mock recorder for MocktrackActivitiesRepository.
type MocktrackActivitiesRepositoryMockRecorder struct {
	mock *MocktrackActivitiesRepository
}

// NewMocktrackActivitiesRepository creates a new mock instance.
func NewMocktrackActivitiesRepository(ctrl *gomock.Controller) *MocktrackActivitiesRepository {
	mock := &MocktrackActivitiesRepository{ctrl: ctrl}
	mock.recorder = &MocktrackActivitiesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrackActivitiesRepository) EXPECT() *MocktrackActivitiesRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocktrackActivitiesRepository) Create(ctx context.Context, model trackactivities.TrackActivity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MocktrackActivitiesRepositoryMockRecorder) Create(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocktrackActivitiesRepository)(nil).Create), ctx, model)
}

// Get mocks base method.
func (m *MocktrackActivitiesRepository) Get(ctx context.Context, userId uint, spotifyId string) (*trackactivities.TrackActivity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userId, spotifyId)
	ret0, _ := ret[0].(*trackactivities.TrackActivity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MocktrackActivitiesRepositoryMockRecorder) Get(ctx, userId, spotifyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MocktrackActivitiesRepository)(nil).Get), ctx, userId, spotifyId)
}

// GetBulkSpotifyIDs mocks base method.
func (m *MocktrackActivitiesRepository) GetBulkSpotifyIDs(ctx context.Context, userId uint, spotifyIds []string) (map[string]trackactivities.TrackActivity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBulkSpotifyIDs", ctx, userId, spotifyIds)
	ret0, _ := ret[0].(map[string]trackactivities.TrackActivity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBulkSpotifyIDs indicates an expected call of GetBulkSpotifyIDs.
func (mr *MocktrackActivitiesRepositoryMockRecorder) GetBulkSpotifyIDs(ctx, userId, spotifyIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBulkSpotifyIDs", reflect.TypeOf((*MocktrackActivitiesRepository)(nil).GetBulkSpotifyIDs), ctx, userId, spotifyIds)
}

// Update mocks base method.
func (m *MocktrackActivitiesRepository) Update(ctx context.Context, model trackactivities.TrackActivity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MocktrackActivitiesRepositoryMockRecorder) Update(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MocktrackActivitiesRepository)(nil).Update), ctx, model)
}
